### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by DJBenson** [JRascagneres/HA-NationalGrid#1]
Just installed and getting "Invalid API Key" with a newly created ELEXON account.

<img width="576" alt="image" src="https://github.com/JRascagneres/HA-NationalGrid/assets/1013909/0bde6cc4-3a97-4398-b71f-66905b0a4573">

**Comment by DJBenson** [comment]
It seems the key works after a short time after signing up. Will close this.

**Comment by JRascagneres** [comment]
Ah thanks. I'll make sure to add a note to the README.
