### ISSUE TITLE
Lost around 25 entities this morning

### ISSUE THREAD

**Issue by darrenaf** [JRascagneres/HA-NationalGrid#10]
Hello.

Around 9am today I lost all the data coming from around 25 entities on the National Grid Integration.   I've reloaded and updated the HA, but it's just saying 
This entity is no longer being provided by the national_grid integration. If the entity is no longer in use, delete it in settings.
Any idea if its just me or a bigger issue?
Thanks

**Comment by JRascagneres** [comment]
@darrenaf Hi. Yeah national grid randomly changed their date format which broke it. You need to upgrade the integration, I've made a new release a couple hours ago

**Comment by darrenaf** [comment]
Yep, thats fixed it, thanks.    The odd thing is it wasnt showing as an update under settings, so I redownloaded the Integration and everything came back online.
  

  
Thanks.
  

  

  
  

  
  
  
  
>

**Comment by darrenaf** [comment]
Looks like National Grid may have changed their date format back again.    Readings went offline about an hour ago again.
  

  

  

  
  
  
  
  
>

**Comment by JRascagneres** [comment]
> Looks like National Grid may have changed their date format back again. Readings went offline about an hour ago again.
> […](#)
> On Jul 10, 2024 at 21:59, Jacques Rascagneres ***@***.***> wrote: @darrenaf Hi. Yeah national grid randomly changed their date format which broke it. You need to upgrade the integration, I've made a new release a couple hours ago — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

I just took a look. Seems to be a different reason this time. Just saw my logs. Its attempting to access the grid data but its not giving data:

```
https://data.elexon.co.uk/bmrs/api/v1/datasets/FUELINST?publishDateTimeFrom=2024-07-11T10:00:04Z&publishDateTimeTo=2024-07-11T11:00:04Z&format=json
```

See here, no data. Seems to be broken on their end, not a lot I can do.
