### ISSUE TITLE
14-day wind sensor seems to have stopped updating?

### ISSUE THREAD

**Issue by ando2040** [JRascagneres/HA-NationalGrid#12]
Hey Jacques, hope you are well. I suspect the below is not your issue, but it's possible the API has been changed and you need to pick up a new source?

`sensor.national_grid_wind_forecast_fourteen_day` currently ends only 8 days away! 
```
  - start_time: "2024-11-04T22:00:00+00:00"
    generation: 8577
```
It's also not changing, and massively diverged from `sensor.national_grid_wind_forecast` - which is how I noticed a few days ago - I waited to see if it corrected but it doesn't seem to be. The embedded 14-day wind sensor does go out to `start_time: "2024-11-08T22:00:00+00:00"`

`sensor.national_grid_wind_forecast_now_to_three_day` has also diverged from the latest forecast but is still currently providing 3 days.

**Comment by ando2040** [comment]
Just fixed itself - assume without intervention in the end. Was out for over a week...

**Comment by ando2040** [comment]
Just fixed itself - assume without intervention in the end. Was out for over a week...

**Comment by JRascagneres** [comment]
Sorry, I completely forgot to respond here. Yeah, some APIs / responsibility changed hands. Essentially ESO split off from NG and so some APIs seemed to go wonky for a minute. Seems okay now.
