### ISSUE TITLE
Integrating DFS dates

### ISSUE THREAD

**Issue by garethcook** [JRascagneres/HA-NationalGrid#3]
Feature request: add DFS support please 

[https://jamiej.co.uk/blog/updated-sensor-yam-for-2023-24-adding-national-grids-dfs-dates-to-home-assistant/](url)

**Comment by JRascagneres** [comment]
I'll look into this, should be easy enough

**Comment by JRascagneres** [comment]
I can implement this data - https://www.nationalgrideso.com/data-portal/demand-flexibility-service/dfs_industry_notification
Will work on it over weekend.

**Comment by deltamelter** [comment]
You can also use the same API as you use for the other ESO data.  Found this one which grabs the requirements
`https://api.nationalgrideso.com/api/3/action/datastore_search?resource_id=ed7019b0-32b7-425c-a2fb-5ba9e32733fb`

**Comment by JRascagneres** [comment]
Yup

**Comment by JRascagneres** [comment]
I think I'll opt for integrating just this one:
```
https://api.nationalgrideso.com/api/3/action/datastore_search?resource_id=7914dd99-fe1c-41ba-9989-5784531c58bb
```

Not sure how best to do it to avoid hitting any kind of capacity limits on the data. 

What are you after? Just any 'upcoming' sessions? and presumably who's eligible for each so you can filter down to your provider?
@garethcook

**Comment by garethcook** [comment]
> I think I'll opt for integrating just this one:
> 
> ```
> 
> https://api.nationalgrideso.com/api/3/action/datastore_search?resource_id=7914dd99-fe1c-41ba-9989-5784531c58bb
> 
> ```
> 
> 
> 
> Not sure how best to do it to avoid hitting any kind of capacity limits on the data. 
> 
> 
> 
> What are you after? Just any 'upcoming' sessions? and presumably who's eligible for each so you can filter down to your provider?
> 
> @garethcook 

Upcoming sessions, yes. As of now they are not that frequent but do get released on the day. We'd need to look at the historical data but I recall it being mid morning. Eligibility could be useful

**Comment by garethcook** [comment]
Here's the historical notification data [https://www.nationalgrideso.com/data-portal/demand-flexibility-service/dfs_industry_notification](url)

The times vary from 08:00 to 15:00. First thoughts are at 9am, midday and 3pm (or perhaps offset by 30 mins, 9.30, 12.30 and 15.30). Is there a push service to avoid pulling from via API?

**Comment by JRascagneres** [comment]
I'll need to pull from the API. I can be fairly lazy and do it in my current schedule which is 5 minutes.

**Comment by JRascagneres** [comment]
@garethcook I've added DFS requirements. It uses this data - https://www.nationalgrideso.com/data-portal/demand-flexibility-service/dfs_service_requirements

It shows from, to, requirement, requirement type, despatch type and eligible participants.

Currently its in the 'beta' version I'm working on that adds requests from the other issue too. - https://github.com/JRascagneres/HA-NationalGrid/releases/tag/v0.0.35

Take a peek at it.

**Comment by JRascagneres** [comment]
Let me know if this meets what you needed :) @garethcook

**Comment by JRascagneres** [comment]
There was an issue - Fixed it in latest https://github.com/JRascagneres/HA-NationalGrid/releases/tag/v0.0.37

**Comment by garethcook** [comment]
Superb. Now - how on earth do I use it :-) I'm on Octopus, I see many different sections for Octopus, and I'm not sure how you determine to which one belongs. Ending up with a datetime entity would be ideal, that change can be used in automations.

**Comment by JRascagneres** [comment]
You'd have to write a template sensor or something to query it to find the item that includes octopus as a supplier.

If you're just on octopus and you just want the saving session time I'd use the octopus integration.

**Comment by JRascagneres** [comment]
Like I say I recommend using the octopus integration but you can play around with template work. Like this filters the results down to a list of DFS events that have Octopus eligible and are in the future:
```
{{ state_attr('sensor.national_grid_dfs_requirements', 'requirements') | selectattr('participants_eligible', 'search', 'OCTOPUS ENERGY LIMITED') | list | rejectattr('end_time', 'lt', now()) | list }}
```

**Comment by garethcook** [comment]
> Like I say I recommend using the octopus integration but you can play around with template work. Like this filters the results down to a list of DFS events that have Octopus eligible and are in the future:
> 
> ```
> {{ state_attr('sensor.national_grid_dfs_requirements', 'requirements') | selectattr('participants_eligible', 'search', 'OCTOPUS ENERGY LIMITED') | list | rejectattr('end_time', 'lt', now()) | list }}
> ```

Excellent, thankyou!

**Comment by garethcook** [comment]
I implemented your script above, and usually the sensor just displays [] on the dashboard. Until a couple of days ago where the DFS slots became active, where it changed to unknown. 

Is there merit in pulling some log data to understand if it's the script or otherwise to establish the correct values? Ta

**Comment by JRascagneres** [comment]
Yeah `[]` would be expected here, what I gave is not a full implementation. 
I'd highly recommend using the octopus integration in this case; getting exactly what you want without full understanding isn't super easy and I can't easily make what you want work for all providers.

**Comment by garethcook** [comment]
I have used the Octopus integration for a while, but it won't give you advance notice of slots where this DFS linkage would allowing for some automation ahead of time, and earlier notification before Octopus. I'll take another look at your code, thanks.

**Comment by deltamelter** [comment]
My "Savey Davey" automation triggered today at 9am an notified me of req change but the notification automation didn't like the second condition based on the above template test
Weird because it works in the template testbed and if I change state manually to test gave me... "Test session today between 1700-1800"

**Comment by deltamelter** [comment]
![Screenshot_20240208_123004_Opera](https://github.com/JRascagneres/HA-NationalGrid/assets/27061628/27757287-7ed7-4c8a-b38f-97a0e9fcfbb3)

**Comment by garethcook** [comment]
> ![Screenshot_20240208_123004_Opera](https://private-user-images.githubusercontent.com/27061628/303339846-27757287-7ed7-4c8a-b38f-97a0e9fcfbb3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTgzMjcsIm5iZiI6MTcwNzM5ODAyNywicGF0aCI6Ii8yNzA2MTYyOC8zMDMzMzk4NDYtMjc3NTcyODctN2VkNy00YzhhLWIzOGYtOTdhMGU5ZmNmYmIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzMTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZmU3OGVjNjFlZTRiMzg1MDYzN2VjMzc5ZWQyMzY5OGIwMWI4ZDU2N2NjMzcxNDkwOTVmOWZiMGQ1MmNmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nx-1BreBwyEv3B-HINMpPXqLQIH5nCqpXFuo-oXEvXg)

Can I have your code please? :-) Thanks

**Comment by deltamelter** [comment]
> Can I have your code please? :-) Thanks

I use a value template condition based on the code from JRascagneres above:
![image](https://github.com/JRascagneres/HA-NationalGrid/assets/27061628/56f581d7-b740-40ae-b54c-6ed3a61e02fe)

**Comment by garethcook** [comment]
> > Can I have your code please? :-) Thanks
> 
> I use a value template condition based on the code from JRascagneres above: ![image](https://private-user-images.githubusercontent.com/27061628/304901031-56f581d7-b740-40ae-b54c-6ed3a61e02fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTE3NDcsIm5iZiI6MTcwNzk5MTQ0NywicGF0aCI6Ii8yNzA2MTYyOC8zMDQ5MDEwMzEtNTZmNTgxZDctYjc0MC00MGFlLWI1NGMtNmVkM2E2MWUwMmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEwMDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNDQ2NzAyMGIwZDU3MGQyYzNlOWY4MTA5NTJhNzU1MWM1NTVlYTFjYWI4ODQyNzE5OWJlODdmZDE5NTRmZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7eYVjjROh-Z-Hk5-FNxy8sbZIeK6rFp5w8PlBVvBksY)

Looks way better than my attempt, would you be OK sharing the yaml, please?
