### ISSUE TITLE
Frequency measurement as a HA entity

### ISSUE THREAD

**Issue by philpem** [JRascagneres/HA-NationalGrid#8]
Just a quick question from someone with very little knowledge of HA APIs and addons!

I notice the Elexon APIs provide information about the current grid frequency: https://bmrs.elexon.co.uk/api-documentation/endpoint/system/frequency

Would it be possible to extend this addon to bring that data in?

I have local grid voltage/frequency monitors but I'm curious how the numbers compare to the official ones. Also my local sensors have quite a coarse resolution compared to the data sent by the Elexon API.

**Comment by JRascagneres** [comment]
Yeah I can probably look at adding that. Should be easy enough

**Comment by JRascagneres** [comment]
@philpem This is done :)
